### ISSUE TITLE
[BUG] TFT returns NaN values in raw outputs

### ISSUE THREAD

**Issue by JeremyKulcsarDS** [sktime/pytorch-forecasting#1756]
### **Describe the bug**

Hi, I am trying to use the library for a personal project.
However, I noticed after training that the outputs were all NaN values.

To make sure the issue wasn't from the data or implementation, I copy pasted the code found in the following page: 
https://pytorch-forecasting.readthedocs.io/en/stable/tutorials/stallion.html

However, I see that the outputs are also all NaN instead of real values like in the tutorial.

Namely, 
```
raw_predictions = best_tft.predict(val_dataloader, mode="raw", return_x=True)
print(raw_predictions.output)
```
Returns tensors of NaNs:
```
Output(prediction=tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
...
```

I noticed that this doesn't happen when I set the architecture hyperparameters to 1:
```
hidden_size=1, 
attention_head_size=1,
hidden_continuous_size=1,
```
Results aren't NaN values, even though they are pretty bad in terms of predictive performance.

So I suspect this isn't an error linked to the library, but either versions of modules or something due to the fact that I run the code on a mac.

Anyone got an idea of what is happening? Thanks!

### **To Reproduce**

Code can be found at:
https://pytorch-forecasting.readthedocs.io/en/stable/tutorials/stallion.html

Before importing `torch`, add:
```
import os
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
```
Otherwise it returns an error because it isn't implemented yet on MPS.

### **Versions**

<details>

```
System:
    python: 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]
executable: [/usr/local/bin/python3](https://file+.vscode-resource.vscode-cdn.net/usr/local/bin/python3)
   machine: macOS-15.2-arm64-arm-64bit

Python dependencies:
          pip: 24.3.1
       sktime: 0.35.0
      sklearn: 1.5.2
       skbase: 0.12.0
        numpy: 2.0.2
        scipy: 1.15.1
       pandas: 2.2.3
   matplotlib: 3.9.2
       joblib: 1.4.2
        numba: None
  statsmodels: 0.14.4
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 2.5.0
   tensorflow: 2.18.0
```
Also, I am using a Macbook Pro M2.

</details>
